spring.application.name=flight-management-service
spring.datasource.url=jdbc:postgresql://localhost:5432/skysyncdb
spring.datasource.username=bugrahan
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ayarlar? (Tablolar? otomatik olu?turmas? için)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Tüm actuator uç noktalar?n? aç (Normalde sadece güvenli olanlar aç?kt?r)
management.endpoints.web.exposure.include=*
# Prometheus'un anlayaca?? formatta veri üretmesini sa?la
management.prometheus.metrics.export.enabled=true